language: node_js
node_js: v14
cache: npm

script: npm run build

env:
- PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

deploy:
  provider: pages
  github-token: $GH_TOKEN
  local-dir: ./public
  skip-cleanup: true
  on:
    branch: master
