# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thomas Parisot
subtitle: Public talks, workshops and events about Web technologies and human experience.
description: |
  I develop my ideas and share the knowledge by using many formats, ranging
  from public speaking, collaborative workshops and down-to-earth events (free or paid).
author: Thomas Parisot
email: hi@thom4.net
default_cover: https://thom4.net/assets/avatar.avif
lang: en-GB
timezone: Europe/Paris

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://thom4.net/talks
root: /talks/
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: ""
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "**/*/slides/*"

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: talk
titlecase: false # Transform title into titlecase
filename_case: 1
render_drafts: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: thom4
layout: talks

nunjucks:
  autoescape: true
  throwOnUndefined: false
  watch: false

pretty_urls:
  trailing_html: false
  trailing_index: false

external_link:
  enabled: true

markdown:
  render:
    html: true
    xhtmlOut: false
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ยง
  plugins:
  - markdown-it-abbr
  - markdown-it-bracketed-spans
  - markdown-it-attrs
  - markdown-it-footnote
  - markdown-it-ins
  - markdown-it-sub
  - markdown-it-sup

# Content Indexing
## See https://www.npmjs.com/package/hexo-algolia
algolia:
  applicationID: 'QIP7Z1PL3B'
  apiKey: '5caf0f682ba8349e8a67872b9edde3f3'
  indexName: 'prod_blog'
  chunkSize: 5000
