# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and deploy pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
    - .gitignore
    - _config.dev.yml
    - 'bin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://oncletom.io/talks/
    steps:
    # Setup
    - uses: actions/checkout@v2
    - name: Use Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm
    - run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1

    # Build
    - run: npm run build
      env:
        NODE_ENV: production

    # Deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
